name: otpauth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  flutter_localizations: 
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  localization: ^2.1.0
  material_color_utilities: ^0.5.0
  otp: ^3.1.4
  qr_code_scanner: ^1.0.1
  flat: ^0.4.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - i18n/